name: Docker Image Publish

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v2
      with:
        # Container registry username
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9D993393D01942A384CD4AA38B6346AE }}
        # Container registry password
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_B2E73E9E60E3471B947D942DFBC388EF }}
        # Container registry server url
        login-server: sampleappaoaichatgpt.azurecr.io
        
    - name: Build the Docker image
      run:         
        docker build . --file Dockerfile --tag sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:latest;
        docker push sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:latest;
      
